export const mockPessoasResponse = {
  totalPages: 2,
  content: [
    {
      id: 1,
      nome: "João Santos",
      idade: 28,
      sexo: "MASCULINO",
      vivo: false,
      urlFoto: null,
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-08-15T10:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Cuiabá - MT",
        ocoId: 101,
      },
    },
    {
      id: 2,
      nome: "Maria Quiteria",
      idade: 45,
      sexo: "FEMININO",
      vivo: true,
      urlFoto: "https://i.pravatar.cc/300?img=25",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-07-20T14:30:00.000Z",
        dataLocalizacao: "2025-07-22",
        localDesaparecimentoConcat: "Várzea Grande - MT",
        ocoId: 102,
      },
    },
    {
      id: 3,
      nome: "Carlos Bolsonaro",
      idade: 19,
      sexo: "MASCULINO",
      vivo: false,
      urlFoto: "https://i.pravatar.cc/300?img=51",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-09-01T22:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Rondonópolis - MT",
        ocoId: 103,
      },
    },
    {
      id: 4,
      nome: "Ana Mendes",
      idade: 33,
      sexo: "FEMININO",
      vivo: false,
      urlFoto: null,
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-08-30T08:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Sinop - MT",
        ocoId: 104,
      },
    },
    {
      id: 5,
      nome: "Pedro Almeida",
      idade: 22,
      sexo: "MASCULINO",
      vivo: false,
      urlFoto: "https://i.pravatar.cc/300?img=12",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-08-25T19:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Tangará da Serra - MT",
        ocoId: 105,
      },
    },
    {
      id: 6,
      nome: "Juliana Costa",
      idade: 35,
      sexo: "FEMININO",
      vivo: true,
      urlFoto: null,
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-06-10T11:00:00.000Z",
        dataLocalizacao: "2025-06-15",
        localDesaparecimentoConcat: "Cáceres - MT",
        ocoId: 106,
      },
    },
    {
      id: 7,
      nome: "Ricardo Gomes",
      idade: 51,
      sexo: "MASCULINO",
      vivo: false,
      urlFoto: "https://i.pravatar.cc/300?img=33",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-08-05T17:45:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Sorriso - MT",
        ocoId: 107,
      },
    },
    {
      id: 8,
      nome: "Fernanda Lima",
      idade: 25,
      sexo: "FEMININO",
      vivo: false,
      urlFoto: "https://i.pravatar.cc/300?img=47",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-07-28T12:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Lucas do Rio Verde - MT",
        ocoId: 108,
      },
    },
    {
      id: 9,
      nome: "Bruno Martins",
      idade: 30,
      sexo: "MASCULINO",
      vivo: true,
      urlFoto: null,
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-05-01T09:20:00.000Z",
        dataLocalizacao: "2025-05-10",
        localDesaparecimentoConcat: "Primavera do Leste - MT",
        ocoId: 109,
      },
    },
    {
      id: 10,
      nome: "Lúcia Ferreira",
      idade: 62,
      sexo: "FEMININO",
      vivo: false,
      urlFoto: "https://i.pravatar.cc/300?img=36",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-09-02T13:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Barra do Garças - MT",
        ocoId: 110,
      },
    },
    {
      id: 11,
      nome: "Marcos Vinicius",
      idade: 17,
      sexo: "MASCULINO",
      vivo: false,
      urlFoto: null,
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-08-22T23:00:00.000Z",
        dataLocalizacao: null,
        localDesaparecimentoConcat: "Alta Floresta - MT",
        ocoId: 111,
      },
    },
    {
      id: 12,
      nome: "Beatriz Santos",
      idade: 29,
      sexo: "FEMININO",
      vivo: true,
      urlFoto: "https://i.pravatar.cc/300?img=1",
      ultimaOcorrencia: {
        dtDesaparecimento: "2025-04-12T18:00:00.000Z",
        dataLocalizacao: "2025-04-20",
        localDesaparecimentoConcat: "Pontes e Lacerda - MT",
        ocoId: 112,
      },
    },
  ],
};
